### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth' in blender 4.2

### ISSUE THREAD

**Issue by team2-research-easy** [loonaticx/blender-egg-importer#5]
when importing egg model in blender 4.2. i get the error

Traceback (most recent call last):
  File "C:\Users\SYS-73\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender-egg-importer-master\__init__.py", line 101, in execute
    root.build_tree(context)
  File "C:\Users\SYS-73\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender-egg-importer-master\importer.py", line 1197, in build_tree
    child.build_tree(context, parent, inv_matrix, under_dart)
  File "C:\Users\SYS-73\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender-egg-importer-master\importer.py", line 1549, in build_tree
    data.use_auto_smooth = True
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'

**Comment by loonaticx** [comment]
Hello! Thanks for your report. Can you please provide me an egg file that is causing this problem to occur?

**Comment by loonaticx** [comment]
Should be fixed in commit bdc867c1c847e2403359f0886411451b2c9c8c22
Thanks for your report!
